# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'web logs'
tagline:             ''
description:         'web and learning logs of @srrvnn'
url:                 http://srrvnn.me
baseurl:             /

# About/contact
author:
  name:              Saravanan Ganesh
  url:               https://twitter.com/srrvnn
  email:             srrvnn@live.com

# Custom vars
version:             1.0.0
