# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'web logs'
tagline:             'of @srrvnn'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://srrvnn.info
baseurl:             /
paginate:            

# About/contact
author:
  name:              Saravanan Ganesh
  url:               https://twitter.com/srrvnn
  email:             srrvnn@live.com

# Custom vars
version:             1.0.0
