# Dependencies
markdown:            redcarpet
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'web logs'
tagline:             ''
description:         'web and learning logs of @srrvnn'
url:                 srrvnn.github.io
baseurl:             /

# About/contact
author:
  name:              Saravanan Ganesh
  url:               https://twitter.com/srrvnn
  email:             srrvnn@live.com

# Custom vars
version:             1.0.0
